### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus_charge_period_card#1]
- [x] Handle 'unavailable' values better
- [x] Handle hass disconnection/reconnection better
- [x] am/pm toggle renders in a weird place on Android
